<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
    
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // List Mode ?>
<div class="container_12">
	<div class="grid_12">
		<ol class="products-list meigee-widget" id="products-list">
			<?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				<?php
					$keyword = 'label-sale';
					$labelstring = MAGE::helper('ThemeOptions')->getProductLabels($_product);
					$isKeyAvaliable = false;
					if(strpos($labelstring, $keyword)){
						$isKeyAvaliable = true;
					}
				?>
				<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?><?php if($isKeyAvaliable == true){echo ' onsale';} ?>">
					<?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductLabels($_product); ?>
					<?php // Product Image ?>
					<div class="grid_3 alpha">
						<div class="product-img-box">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(290, null); ?>" <?php echo MAGE::helper('ThemeOptions/Retina')->getRetinaData('widget_list', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 290, 580); ?></div></a>
							<?php // Fancybox
							if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
								<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
							<?php endif; // End Fancybox ?>
						</div>
					</div>
					<?php // Product description ?>
					<div class="grid_9 omega">
						<div class="list-container">
							<div class="indent">
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
								<?php echo $this->getPriceHtml($_product, true) ?>
								<?php if($_product->getRatingSummary()): ?>
								<?php echo $this->getReviewsSummaryHtml($_product) ?>
								<?php endif; ?>
								<?php if(!$_product->isSaleable()): ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
								<div class="clear"></div>                
								<div class="desc std">
									<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
								</div>
							</div>
							<div class="actions">
								<ul class="add-to-links">
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
									<?php endif; ?>
									<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
									<?php endif; ?>
								</ul>
								<?php if($_product->isSaleable()): ?>
									<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>                                    
								<?php endif; ?>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				</li>
			<?php if (++$i == $_collectionSize ) break; endforeach; ?>
		</ol>
	</div>
	<div class="clear"></div>
</div>
<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>