<?php
    $_productCollection = $this->getMyCollection();
	$gridMode = $this->sliderGridSelection();
	$visibleProducts = $this->getData('visible_products');
	$productCount = count($_productCollection);
	if (count($_productCollection)) {
	
		$category = $this->catName();
		$_helper = $this->helper('catalog/output');
		$_collectionSize = $this->productsAmount();

		$randId = $this->getWidgetId();
		
		$fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Slider ?>
<div class="container_12 widget-slider-box">
<?php if($productCount > $visibleProducts): ?>
	<div class="<?php echo $gridMode; ?>">
		<div class="slider-container widget-container">
			<div class="home-container">
				<div class="home-slider-conainer" id="home-slider-<?php echo $randId; ?>">
					<div class="home-slider es-carousel-wrapper">
						<div class="widget-slider">
							<ul class="products-grid carousel-ul">
								<?php $i=0; foreach ($_productCollection as $_product): ?>
								<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
								<?php
									$keyword = 'label-sale';
									$labelstring = MAGE::helper('ThemeOptions')->getProductLabels($_product);
									$isKeyAvaliable = false;
									if(strpos($labelstring, $keyword)){
										$isKeyAvaliable = true;
									}
								?>
								<li class="item<?php if($isKeyAvaliable == true){echo ' onsale';} ?>">
									<div class="indent">
										<div class="product-box">
											<div class="product-img-box">
												<?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductLabels($_product); ?>
												<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(275, null); ?>" <?php echo MAGE::helper('ThemeOptions/Retina')->getRetinaData('widget_slider', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 275, 550); ?></div></a>
												<?php  // Fancybox
												if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
														<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
													<?php endif;
												// End Fancybox ?>
											</div>
											<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>                        
											<div class="actions">
												<?php if($_product->isSaleable()): ?>
													<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
												<?php else: ?>
													<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
												<?php endif; ?>
												<?php echo $this->getPriceHtml($_product, true) ?>
												<div class="clear"></div>
											</div>
										</div>
									</div>
								</li>
								<?php if (++$i > $_collectionSize-1 ) break; endforeach ?>
							</ul>
						</div>
					</div>
					<div class = 'next'></div>
					<div class = 'prev unselectable'></div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	<script type="text/javascript">
		jQuery(window).load(function(){
			jQuery('#home-slider-<?php echo $randId; ?> .widget-slider').iosSlider({
			  responsiveSlideWidth: true,
			  snapToChildren: true,
			  desktopClickDrag: true,
			  infiniteSlider: true
			  <?php echo $this->getSliderOptions(); ?>,
			  navNextSelector: '#home-slider-<?php echo $randId; ?> .next',
			  navPrevSelector: '#home-slider-<?php echo $randId; ?> .prev'
			  <?php if(isset($sliderConfig ['autoSlide'])): ?>, autoSlide: <?php echo $sliderConfig ['autoSlide']; ?><?php endif; ?>
			  <?php if(isset($sliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $sliderConfig ['autoSlideTimer']; ?><?php endif; ?>
			});
			
			function widget_slider_height_<?php echo $randId; ?>(){
				var widget_slider_height = 0;
				jQuery('.widget-container #home-slider-<?php echo $randId; ?> .products-grid li.item').each(function(){
					if(jQuery(this).height() > widget_slider_height){
						widget_slider_height = jQuery(this).height();
					}
				})
				jQuery('.widget-container #home-slider-<?php echo $randId; ?> .widget-slider').css('min-height', widget_slider_height+12);
			}
			widget_slider_height_<?php echo $randId; ?>();
			jQuery(window).resize(function(){widget_slider_height_<?php echo $randId; ?>();});
		  });
	</script>
	</div>
	<div class="clear"></div>
	<?php else: ?>
		<div class="no-widget"><?php echo $this->__("Warning: Please make sure you have %s+ products to display in the slider, otherwise widget won't be displayed", $visibleProducts+1) ?></div>
	<?php endif; ?>
</div>
<?php 
	unset ($randId);
}
?>