<?php
    $_productCollection = $this->getMyCollection();
	$gridMode = $this->sliderGridSelection2();
	$visibleProducts = $this->getData('visible_products_2');
	$productCount = count($_productCollection);
	if (count($_productCollection)) {
	
		$category = $this->catName();
		$_helper = $this->helper('catalog/output');
		$_collectionSize = $this->productsAmount();

		$randId = $this->getWidgetId();
		
		$fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Slider ?>
<div class="home-slider-wrapper slider-2-wrapper">
	<div class="container_12">
	<?php if($productCount > $visibleProducts): ?>
		<div class="grid_12">
			<div class="slider-container slider-2 widget-container">
				<?php if($this->getData("block_position") == 1): ?>
				<div class="slider-text-box grid_3 alpha">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getData("static_block"))->toHtml() ?>
				</div>
				<?php endif; ?>
				<div class="home-container<?php if($this->getData("block_position") == 1){echo ' grid_9 omega';}elseif($this->getData("block_position") == 2){echo ' grid_9 alpha';}else{echo ' no-static-block '.$gridMode.' alpha omega';} ?>">
					<div class="home-slider-conainer">
						<div class="home-slider es-carousel-wrapper" id="home-slider-<?php echo $randId; ?>">
							<div class="widget-slider">
								<ul class="products-grid carousel-ul">
									<?php $i=0; foreach ($_productCollection as $_product): ?>
									<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
									<li class="item">
										<div class="indent">
											<div class="product-img-box">
												<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(275, null); ?>" <?php echo MAGE::helper('ThemeOptions/Retina')->getRetinaData('widget_slider_2', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><span class="image-box"></span><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 275, 550); ?></a>
												<?php // Fancybox
												if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
													<a class="fancybox" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
												<?php endif; // End Fancybox ?>
											</div>
											<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
											<?php echo $this->getPriceHtml($_product, true) ?>
											<?php if($_product->getRatingSummary()): ?>
											<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
											<?php endif; ?>
											<div class="clear"></div>
										</div>
									</li>
									<?php if (++$i > $_collectionSize-1 ) break; endforeach ?>
								</ul>
							</div>
							<div class = 'next'><em>&nbsp;</em><span>&nbsp;</span></div>
							<div class = 'prev unselectable'><em>&nbsp;</em><span>&nbsp;</span></div>
						</div>
					</div>
				</div>
				<?php if($this->getData("block_position") == 2): ?>
				<div class="slider-text-box grid_3 omega">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getData("static_block"))->toHtml() ?>
				</div>
				<?php endif; ?>
				<div class="clear"></div>
			</div>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		<script type="text/javascript">
			jQuery(window).load(function(){
				jQuery('#home-slider-<?php echo $randId; ?> .widget-slider').iosSlider({
				  responsiveSlideWidth: true,
				  snapToChildren: true,
				  desktopClickDrag: true,
				  infiniteSlider: true
				  <?php if(isset($sliderConfig ['autoSlide'])): ?>, <?php echo $this->getSliderOptions(); ?><?php endif; ?>
				  , navNextSelector: '#home-slider-<?php echo $randId; ?> .next',
				  navPrevSelector: '#home-slider-<?php echo $randId; ?> .prev'
				  <?php if(isset($sliderConfig ['autoSlide'])): ?>, autoSlide: <?php echo $sliderConfig ['autoSlide']; ?><?php endif; ?>
				  <?php if(isset($sliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $sliderConfig ['autoSlideTimer']; ?><?php endif; ?>
				});
				
				function widget_slider_height_<?php echo $randId; ?>(){
					var widget_slider_height = 0;
					jQuery('.widget-container #home-slider-<?php echo $randId; ?> .products-grid li.item').each(function(){
						if(jQuery(this).height() > widget_slider_height){
							widget_slider_height = jQuery(this).height();
						}
					})
					jQuery('.widget-container #home-slider-<?php echo $randId; ?> .widget-slider').css('min-height', widget_slider_height+2);
				}
				widget_slider_height_<?php echo $randId; ?>();
				jQuery(window).resize(function(){widget_slider_height_<?php echo $randId; ?>();});
			  });
		</script>
		</div>
		<div class="clear"></div>
		<?php else: ?>
			<div class="no-widget"><?php echo $this->__("Warning: Please make sure you have %s+ products to display in the slider, otherwise widget won't be displayed", $visibleProducts+1) ?></div>
		<?php endif; ?>
	</div>
</div>
<?php 
	unset ($randId);
}
?>