<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();

    $randId = $this->getWidgetId();
    
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Slider ?>
<div class="home-slider-wrapper">
	<div class="container_12">
		<div class="grid_12">
			<div class="slider-container small-slider widget-container">
				<div class="home-container grid_5 alpha">
					<div class="home-slider-conainer">
						<div class="home-slider es-carousel-wrapper" id="home-slider-<?php echo $randId; ?>">
							<div class="widget-slider">
								<ul class="products-grid carousel-ul">
									<?php $i=0; foreach ($_productCollection as $_product): ?>
									<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
									<li class="item">
										<div class="indent">
											<div class="product-img-box">
												<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300, null); ?>" <?php echo MAGE::helper('ThemeOptions/Retina')->getRetinaData('widget_slider_small', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><span class="image-box"></span><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 300, 600); ?></a>
											</div>
											<div class="product-details">
												<?php echo $this->getPriceHtml($_product, true) ?>
												<h2 class="product-name<?php if(strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) >= 25 ){echo ' two-rows';} ?>"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
												<?php echo '<p>'.$_product->getShortDescription().'</p>'; ?>
												<button onclick="setLocation('<?php echo $_product->getProductUrl() ?>')" class="button btn-cart" title="Details" type="button"><span><span><?php echo $this->__('View Details') ?></span></span></button>
											</div>
										</div>
									</li>
									<?php if (++$i > $_collectionSize-1 ) break; endforeach ?>
								</ul>
							</div>
							<div class = 'next'><?php echo $this->__('Next') ?></div>
							<div class = 'prev unselectable'><?php echo $this->__('Previous') ?></div>
						</div>
					</div>
				</div>
				<div class="small-slider-text-box grid_7 omega">
					&nbsp;
				</div>
				<div class="clear"></div>
			</div>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		<script type="text/javascript">
			jQuery(window).load(function(){
				jQuery('#home-slider-<?php echo $randId; ?> .widget-slider').iosSlider({
				  responsiveSlideWidth: true,
				  snapToChildren: true,
				  desktopClickDrag: true,
				  infiniteSlider: true
				  <?php if(isset($sliderConfig ['autoSlide'])): ?>, <?php echo $this->getSliderOptions(); ?><?php endif; ?>
				  , navNextSelector: '#home-slider-<?php echo $randId; ?> .next',
				  navPrevSelector: '#home-slider-<?php echo $randId; ?> .prev',
				  onSlideComplete: slideComplete_<?php echo $randId; ?>,
				  onSliderLoaded: sliderLoaded_<?php echo $randId; ?>
				  <?php if(isset($sliderConfig ['autoSlide'])): ?>, autoSlide: <?php echo $sliderConfig ['autoSlide']; ?><?php endif; ?>
				  <?php if(isset($sliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $sliderConfig ['autoSlideTimer']; ?><?php endif; ?>
				});
				
				function widget_slider_height_<?php echo $randId; ?>(){
					var widget_slider_height = 0;
					jQuery('.widget-container #home-slider-<?php echo $randId; ?> .products-grid li.item').each(function(){
						if(jQuery(this).height() > widget_slider_height){
							widget_slider_height = jQuery(this).height();
						}
					})
					jQuery('.widget-container #home-slider-<?php echo $randId; ?> .widget-slider').css('min-height', widget_slider_height+2);
				}
				widget_slider_height_<?php echo $randId; ?>();
				jQuery(window).resize(function(){widget_slider_height_<?php echo $randId; ?>();});
				
				function slideComplete_<?php echo $randId; ?>(args){
					var small_slider_<?php echo $randId; ?>_box = jQuery('.small-slider #home-slider-<?php echo $randId; ?>').parent().parent().parent().find('.small-slider-text-box');
					small_slider_<?php echo $randId; ?>_box.html(jQuery('.small-slider #home-slider-<?php echo $randId; ?> .products-grid li.item:eq(' + ((args.currentSlideNumber)-1) + ') .product-details').html());
				}
				function sliderLoaded_<?php echo $randId; ?>(args){
					slideComplete_<?php echo $randId; ?>(args);
				}
			  });  
		</script>
		</div>
		<div class="clear"></div>
	</div>
</div>
<?php unset ($randId); ?>