<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php 
/*****/
$appearance = MAGE::helper('ThemeOptions')->getThemeOptions('appearance');
/*****/
?>
<?php echo MAGE::helper('ThemeOptions')->getThemeOptions('user-scalable'); ?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->

<!-- Font Replacement -->
<?php if ($appearance['font'] == 2): ?>
<link href='http://fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $appearance['gfont']); ?>:200,300,400,500,600,700,800' rel='stylesheet' type='text/css'>
<?php endif; ?>
<!-- End Font Replacement -->

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<?php if ($appearance['customcolors'] == 1): ?>
<style>
<?php
$titlebg = Mage::getBaseUrl('media') . 'images/' . Mage::getStoreConfig('meigee_general/appearance/titlebg');

if(!empty($titlebg)){
?>
header#header .header-wrapper{background-image:url(<?php echo $titlebg; ?>);}
<?php
}
?>
</style>
<?php endif; ?>

<!-- Font Replacement -->
<?php if ($appearance['font'] == 2): ?>
<?php if ($appearance['default_sizes'] == 0): ?>
<style>
header#header .menu-button,
.slider-2 .slider-text-box h2,
.slider-2 .slider-text-box h3,
.small-slider .home-slider-conainer .prev,
.small-slider .home-slider-conainer .next,
.addresses-list .addresses-primary h2,
.addresses-list .addresses-additional h2,
.dashboard .box-info .box .box-title h3,
.dashboard .box-head h2,
.dashboard .welcome-msg .hello,
.account-login .login-page-box h2,
.error-msg,
.success-msg,
.note-msg,
.notice-msg,
.opc .step h3,
.opc .step-title .number,
.opc .step-title h2,
#cart-accordion h3.accordion-title,
.product-collateral h2,
.cart .crosssell h2,
.cart .totals-title,
.cart .discount h2,
.cart .shipping h2,
.catalog-product-view .box-reviews h2,
.review-title h2,
.block-related header h2,
.meigee-tabs a,
.product-view .product-shop .product-bottom-box .add-to-links li a,
.product-view .product-shop .product-bottom-box .email-friend,
.product-view .product-shop .product-name h2,
.products-list .add-to-links li a,
.price,
.product-name a,
.sorter .view-mode .grid,
.sorter .view-mode .list,
aside.sidebar .block-reorder .actions a,
aside.sidebar .block-wishlist .actions a,
aside.sidebar .block-tags .actions a,
aside.sidebar .block-compare .actions a,
aside.sidebar section header h2,
.sidebar-category h2,
.page-title h1,
.page-title h2,
#footer .footer-wrapper .footer-columns-block h3,
header#header .dropdown-links,
header#header .links li a.top-link-login,
header#header .links li a.top-link-logout,
button.button span span,
header#header .top-cart .block-content .subtotal .price,
header#header .header-links-wrapper .item-link .block-title a,
#nav > li > a,
nav.breadcrumbs li a,
nav.breadcrumbs li strong,
header#header .welcome-msg,
.header-slider-container .iosSlider .slider .item h2,
.header-slider-container .iosSlider .slider .item a{font-family: '<?php echo $appearance['gfont']; ?>', sans-serif; font-size:<?php echo $appearance['fontsize']; ?>px !important; line-height: <?php echo $appearance['fontsize']; ?>px !important; font-weight: <?php echo $appearance['fontweight']; ?> !important;}
</style>
<?php else: ?>
<style>
header#header .menu-button,
.slider-2 .slider-text-box h2,
.slider-2 .slider-text-box h3,
.small-slider .home-slider-conainer .prev,
.small-slider .home-slider-conainer .next,
.addresses-list .addresses-primary h2,
.addresses-list .addresses-additional h2,
.dashboard .box-info .box .box-title h3,
.dashboard .box-head h2,
.dashboard .welcome-msg .hello,
.account-login .login-page-box h2,
.error-msg,
.success-msg,
.note-msg,
.notice-msg,
.opc .step h3,
.opc .step-title .number,
.opc .step-title h2,
#cart-accordion h3.accordion-title,
.product-collateral h2,
.cart .crosssell h2,
.cart .totals-title,
.cart .discount h2,
.cart .shipping h2,
.catalog-product-view .box-reviews h2,
.review-title h2,
.block-related header h2,
.meigee-tabs a,
.product-view .product-shop .product-bottom-box .add-to-links li a,
.product-view .product-shop .product-bottom-box .email-friend,
.product-view .product-shop .product-name h2,
.products-list .add-to-links li a,
.price,
.product-name a,
.sorter .view-mode .grid,
.sorter .view-mode .list,
aside.sidebar .block-reorder .actions a,
aside.sidebar .block-wishlist .actions a,
aside.sidebar .block-tags .actions a,
aside.sidebar .block-compare .actions a,
aside.sidebar section header h2,
.sidebar-category h2,
.page-title h1,
.page-title h2,
#footer .footer-wrapper .footer-columns-block h3,
header#header .dropdown-links,
header#header .links li a.top-link-login,
header#header .links li a.top-link-logout,
button.button span span,
header#header .top-cart .block-content .subtotal .price,
header#header .header-links-wrapper .item-link .block-title a,
#nav > li > a,
nav.breadcrumbs li a,
nav.breadcrumbs li strong,
header#header .welcome-msg,
.header-slider-container .iosSlider .slider .item h2,
.header-slider-container .iosSlider .slider .item a{font-family: '<?php echo $appearance['gfont']; ?>', sans-serif;}
</style>
<?php endif; ?>
<?php endif; ?>
<!-- End Font Replacement -->
<?php if ($appearance['customcolors'] == 1): ?>
<!-- Theme Colors -->
<?php
    function HexToRGB($hex) {
	    $hex = ereg_replace("#", "", $hex);
	    $color = '';
	    
	    if(strlen($hex) == 3) {
		    $color .= hexdec(substr($hex, 0, 1) . $r) . ',';
		    $color .= hexdec(substr($hex, 1, 1) . $g) . ',';
		    $color .= hexdec(substr($hex, 2, 1) . $b);
	    }
	    else if(strlen($hex) == 6) {
		    $color .= hexdec(substr($hex, 0, 2)) . ',';
		    $color .= hexdec(substr($hex, 2, 2)) . ',';
		    $color .= hexdec(substr($hex, 4, 2));
	    }
	    
	    return $color;
    }
?>
<style>
	/*  Site Background */
	.content-wrapper,
	.blocks-wrapper-2 header#header .header-links-wrapper{background-color:#<?php echo $appearance['sitebg']; ?>;}

	/* Skin Color #1 */
	a:hover,
	.price,
	.block-account li strong,
	.product-name a:hover,
	.catalog-product-view .box-reviews .full-review,
	.opc .step h4,
	.small-slider .home-slider-conainer .prev:hover,
	.small-slider .home-slider-conainer .next:hover,
	.slider-2 .slider-text-box h3{color:#<?php echo $appearance['maincolor']; ?>;}
	
	.block-account li:hover span.marker,
	.block-account li.current span.marker,
	#nav > li.over,
	#nav > li.active,
	.sidebar-category,
	#categories-accordion li.level-top.parent .btn-cat.closed,
	.block-layered-nav dl#layered_navigation_accordion dt.closed .btn-nav,
	aside.sidebar section:first-child .sidebar-shadow,
	.block-wishlist .prev:hover,
	.block-wishlist .next:hover,
	.sorter .view-mode strong.list,
	.sorter .view-mode a.list:hover,
	.sorter .view-mode strong.grid,
	.sorter .view-mode a.grid:hover,
	.sorter .sort-by a,
	.sorter .pages li a.i-next,
	.sorter .pages li a.i-previous,
	.sorter .pages .current,
	.sorter .pages li a:hover,
	.products-list .add-to-links li a,
	.product-view .product-shop .product-bottom-box .add-to-links li a,
	.product-view .product-shop .product-bottom-box .email-friend,
	.cart-table .cart-edit:hover,
	.cart-table .link-wishlist:hover,
	.cart-table .btn-remove2:hover,
	.my-wishlist .data-table .btn-remove2:hover,
	.my-wishlist .link-edit:hover,
	.cart-table button.button:hover span,
	.my-wishlist .buttons-set button.button:hover span,
	.cart-table button.btn-continue span,
	.my-account .my-wishlist .buttons-set button.btn-update span,
	.cart .shipping button.button span,
	.cart .discount button.button span,
	.my-wishlist input.quantity-decrease:hover,
	.my-wishlist input.quantity-increase:hover,
	.add-to-cart input.quantity-decrease:hover,
	.add-to-cart input.quantity-increase:hover,
	.cart-table input.quantity-decrease:hover,
	.cart-table input.quantity-increase:hover,
	.cart .totals-title,
	#toTop,
	.opc .active .step-title,
	.account-login .login-page-box .content .buttons-set button span,
	.small-slider .small-slider-text-box .price-box,
	header#header .menu-button,
	aside.sidebar section.active header .sidebar-block-button,
	aside.sidebar section.block-layered-nav .btn-remove,
	#nav ul li.touched,
	#nav ul li.over,
	#nav ul li.active,
	#nav ul,
	#nav div{background-color:#<?php echo $appearance['maincolor']; ?>;}
	
	.nav-wide#nav ul.level0,
	.nav-wide#nav .static-wrapper,
	.my-wishlist input.quantity-decrease:hover,
	.my-wishlist input.quantity-increase:hover,
	.add-to-cart input.quantity-decrease:hover,
	.add-to-cart input.quantity-increase:hover,
	.cart-table input.quantity-decrease:hover,
	.cart-table input.quantity-increase:hover,
	#nav ul,
	#nav div{
		background-color:rgba(<?php echo HexToRGB($appearance['maincolor']); ?>, 0.9);
	}


	@media only screen and (max-width: 767px){
		header#header .nav-container > ul{
			background-color:rgba(<?php echo HexToRGB($appearance['maincolor']); ?>, 0.9);
		}
	}
	
	
	/* Skin Color #2 */
	#footer .twits p a,
	#footer .footer-columns-block .custom_footer p a{color:#<?php echo $appearance['secondcolor']; ?>;}
	
	.block-account li span.marker,
	button.button span,
	#footer .footer-wrapper,
	#footer .footer-indent li a:hover,
	#footer .footer-wrapper .footer-columns-block ul li a:hover,
	.sidebar button.button:hover > span,
	aside.sidebar .block-reorder .actions a:hover,
	aside.sidebar .block-wishlist .actions a:hover,
	aside.sidebar .block-tags .actions a:hover,
	aside.sidebar .block-compare .actions a:hover,
	.sorter .sort-by a:hover,
	.sorter .pages li a.i-next:hover,
	.sorter .pages li a.i-previous:hover,
	.products-list .add-to-links li a:hover,
	.product-view .product-shop .product-bottom-box .add-to-links li a:hover,
	.product-view .product-shop .product-bottom-box .email-friend:hover,
	.meigee-tabs,
	.catalog-product-view .box-reviews .data-table thead,
	.cart-table .cart-edit,
	.cart-table .link-wishlist,
	.cart-table .btn-remove2,
	.my-wishlist .data-table .btn-remove2,
	.my-wishlist .link-edit,
	.my-wishlist input.quantity-decrease,
	.my-wishlist input.quantity-increase,
	.add-to-cart input.quantity-decrease,
	.add-to-cart input.quantity-increase,
	.cart-table input.quantity-decrease,
	.cart-table input.quantity-increase,
	#toTopHover,
	.block-related .prev,
	.block-related .next,
	.product-view .product-prev,
	.product-view .product-next,
	.more-views .prev,
	.more-views .next,
	.slider-container .prev,
	.slider-container .next,
	.header-slider-container .next,
	.header-slider-container .prev{background-color:#<?php echo $appearance['secondcolor']; ?>;}

	.my-wishlist input.quantity-decrease,
	.my-wishlist input.quantity-increase,
	.add-to-cart input.quantity-decrease,
	.add-to-cart input.quantity-increase,
	.cart-table input.quantity-decrease,
	.cart-table input.quantity-increase,
	header#header .top-cart .block-title,
	header#header .top-cart .block-content{
		background-color:rgba(<?php echo HexToRGB($appearance['secondcolor']); ?>, 0.8);
		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#cc<?php echo $appearance['secondcolor']; ?>,endColorstr=#cc<?php echo $appearance['secondcolor']; ?>);
		zoom: 1;
	}

	.header-slider-container .next,
	.header-slider-container .prev,
	.slider-container .prev,
	.slider-container .next,
	.more-views .prev,
	.more-views .next,
	.product-view .product-prev,
	.product-view .product-next,
	.block-related .prev,
	.block-related .next{
		background-color:rgba(<?php echo HexToRGB($appearance['secondcolor']); ?>, 0.8);
	}
	
</style>
<!-- Theme Colors -->
<?php endif; ?>