<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<section class="block-subscribe">
	<div class="item-link-shadow"></div>
	<div class="block-title">
		<div class="item-marker"></div>
		<a><?php echo $this->__('Newsletter') ?></a>
	</div>
	<div class="content-block">
		<div class="indent">
			<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
				<div class="block-content">
					<label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
					<div class="input-box">
						<button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
						<input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
						<div class="clear"></div>
					</div>
				</div>
			</form>
		</div>
	</div>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</section>